package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<html>\r\n<head>\r\n<title>buyBasket</title>\r\n<meta http-equiv=\"Content-Language\" content=\"en-us\"/>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n<title>Untitled 1</title>\r\n<meta http-equiv=\"Page-Enter\" content=\"revealTrans(Duration=1.0,Transition=2)\"/>\r\n<meta name=\"description\" content=\"Visit the online bookshop of MMM\">\r\n<meta name=\"keywords\" content=\"bookshop, bookstore, author, buy books online, book shop, book store, Australia, self help, computers, Australian, books online\">\r\n<meta name=\"robots\" content=\"index, follow\">\r\n<script language=\"javascript\" src=\"Template2_MMM.com_files/stylesheet.js\" type=\"\"></script>\r\n<link rel=\"StyleSheet\" href=\"Template2_MMM.com_files/stylesheet_PCEXP.css\" type=\"text/css\">\r\n<script language=\"javascript\" src=\"Template2_MMM.com_files/functions.js\" type=\"\"></script>\r\n<style type=\"text/css\">\r\n");
      out.write("  <!--\r\n    .style1 {font-size: 12pt}\r\n    .style2 {\r\n    font-size: 14pt;\r\n    color: #FFFFFF;\r\n    }\r\n    .style3 {\r\n    color: #FF0000;\r\n    font-size: 14pt;\r\n    }\r\n  .style6 {\r\n\ttext-align: left;\r\n}\r\n  .style7 {\r\n\ttext-align: right;\r\n}\r\n  -->\r\n</style>\r\n<meta http-equiv=\"Content-Language\" content=\"en-us\"/>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n<title>Untitled 1</title>\r\n<meta http-equiv=\"Page-Enter\" content=\"revealTrans(Duration=1.0,Transition=2)\"/>\r\n</head>\r\n<body>\r\n\r\n\r\n\r\n\r\n\r\n");
      jdbcMySql.MySqlConnector MySqlObj = null;
      synchronized (_jspx_page_context) {
        MySqlObj = (jdbcMySql.MySqlConnector) _jspx_page_context.getAttribute("MySqlObj", PageContext.PAGE_SCOPE);
        if (MySqlObj == null){
          MySqlObj = new jdbcMySql.MySqlConnector();
          _jspx_page_context.setAttribute("MySqlObj", MySqlObj, PageContext.PAGE_SCOPE);
          out.write('\r');
          out.write('\n');

                  if (request.getParameter("UserName") != null && request.getParameter("Password") != null) {
                    String userName;
                    String password;
                    userName = request.getParameter("UserName");
                    password = request.getParameter("Password");
                    try {
                      Connection con = MySqlObj.getDbConnection("mani", "mbh", "3306", "localhost", "3m");
                      ResultSet rslt = MySqlObj.runSqlQuery("select * from users where USERNAME='" + userName + "'", con);
                      if (rslt.next()) {
                        if (rslt.getString("PASSWORD").equals(password)) {
                          session.setAttribute("UserID", String.valueOf(rslt.getInt("ID")));
                          session.setAttribute("UserName", userName);
                          session.setAttribute("UserType", String.valueOf(rslt.getInt("TYPE")));
                          session.setAttribute("basket", new ArrayList());
                          request.getRequestDispatcher("Home.jsp").forward(request, response);
                        }
                        else {
                          out.println("Password is not correct.");
                        }
                      } //end if (rslt.next())
                      else {
                        out.println("UserName is not correct.");
                      }
                    } //end try
                    catch (SQLException e) {
                      e.printStackTrace();
                    }
                    catch (Exception ex) {
                      ex.printStackTrace();
                    }
                  } //end if
                
          out.write("\r\n  <!-- HEADER //-->\r\n  <a name=\"top\">  </a>\r\n  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"770\">\r\n    <tbody>\r\n      <tr>\r\n        <td bgcolor=\"#00563b\" valign=\"top\" width=\"391\">\r\n          <a href=\"http://www.angusrobertson.com.au/\" target=\"_top\" onMouseOver=\"window.status=''; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <img src=\"Template2_MMM.com_files/main01.jpg\" alt=\"Angus &amp; Robertson Book Shop\" border=\"0\" height=\"69\" width=\"391\">\r\n          </a>\r\n        </td>\r\n        <td align=\"right\" bgcolor=\"#ffffff\" valign=\"top\" width=\"379\">\r\n          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n            <tbody>\r\n              <tr>\r\n                <td colspan=\"2\" valign=\"top\">\r\n                  <div align=\"right\">\r\n                    <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"7\" width=\"1\">\r\n                    <br>\r\n                    <a href=\"javascript:launchthawte()\" onMouseOver=\"window.status='View SSL Certificate Info'; return true\" onMouseOut=\"window.status=''; return true\">                      Security by MMM Team\r\n");
          out.write("                      &nbsp;&nbsp;\r\n                      <img src=\"Template2_MMM.com_files/header_ssl.gif\" alt=\"View SSL Certificate Info\" align=\"middle\" border=\"0\" height=\"18\" hspace=\"0\" vspace=\"0\" width=\"17\">\r\n                    </a>\r\n                  </div>\r\n                </td>\r\n                <td valign=\"bottom\" width=\"18\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"18\">\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td valign=\"bottom\">\r\n                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <tbody>\r\n                      <tr>\r\n                        <td valign=\"bottom\">\r\n                          <a href=\"Cart.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n                            <img src=\"Template2_MMM.com_files/header_viewcart.gif\" alt=\"View Cart\" align=\"middle\" border=\"0\" height=\"12\" width=\"57\">\r\n                          </a>\r\n");
          out.write("                        </td>\r\n                        <td>\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"3\">\r\n                        </td>\r\n                        <td valign=\"bottom\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"40\">\r\n                        </td>\r\n                        <td>\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"3\">\r\n                        </td>\r\n                        <td valign=\"bottom\">\r\n                          <a href=\"http://www.angusrobertson.com.au/checkout/viewcart.asp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n                            <img src=\"Template2_MMM.com_files/header_cart.gif\" alt=\" Items\" align=\"bottom\" border=\"0\" height=\"20\" width=\"23\">\r\n                          </a>\r\n                        </td>\r\n                      </tr>\r\n");
          out.write("                    </tbody>\r\n                  </table>\r\n                </td>\r\n                <td align=\"right\" valign=\"bottom\">\r\n                  <a href=\"Credit.jsp\" target=\"_top\" onMouseOver=\"window.status='My Account'; return true\" onMouseOut=\"window.status=''; return true\">\r\n                    <img src=\"Template2_MMM.com_files/header_myaccount.gif\" alt=\"My Account\" border=\"0\" height=\"12\" width=\"67\">\r\n                  </a>\r\n                </td>\r\n                <td>                </td>\r\n              </tr>\r\n            </tbody>\r\n          </table>\r\n        </td>\r\n      </tr>\r\n    </tbody>\r\n  </table>\r\n  <!-- END HEADER //-->\r\n  <!-- NAV //-->\r\n  <table width=\"582\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n    <tbody>\r\n      <tr bgcolor=\"#ffffff\" valign=\"middle\">\r\n        <td colspan=\"12\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n        </td>\r\n      </tr>\r\n      <tr bgcolor=\"#00563b\" valign=\"middle\">\r\n        <td width=\"5\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"5\">\r\n");
          out.write("        </td>\r\n        <td width=\"45\">\r\n          <a href=\"Home.jsp\" target=\"_top\" onMouseOver=\"document.header_nav_home.src='/images/header_nav_home_o.gif'; window.status='Home'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <img src=\"Template2_MMM.com_files/header_nav_home_o.gif\" alt=\"Home\" name=\"header_nav_home\" border=\"0\" height=\"25\" width=\"39\">\r\n          </a>\r\n        </td>\r\n        <td width=\"1\">\r\n          <a href=\"http://www.angusrobertson.com.au/products/newreleases.asp\" target=\"_top\" onMouseOver=\"document.header_nav_newreleases.src='/images/header_nav_newreleases_o.gif'; window.status='New releases'; return true\" onMouseOut=\"document.header_nav_newreleases.src='/images/header_nav_newreleases.gif'; window.status=''; return true\">          </a>\r\n        </td>\r\n        <td width=\"66\" class=\"titlebig whitelhs style1\">\r\n          <a href=\"Search.jsp\" target=\"_top\" class=\"style2\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <span class=\"titlebig whitelhs style1\">Search </span>\r\n");
          out.write("          </a>\r\n        </td>\r\n        <td width=\"47\">\r\n          <span class=\"titlebig whitelhs style1\"> <a href=\"Cart.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\"><span class=\"titlebig whitelhs style1\">Cart </span> </a>\r\n        </td>\r\n        <td width=\"62\">\r\n          <span class=\"titlebig whitelhs style1\"> <a href=\"Credit.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\"><span class=\"titlebig whitelhs style1\">credit </span></a>\r\n        </td>\r\n        <td width=\"50\">\r\n          <a href=\"Login.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <span class=\"titlebig whitelhs style1\">log in </span>\r\n          </a>\r\n        </td>\r\n        <td width=\"78\">\r\n          <a href=\"Signup.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <span class=\"titlebig whitelhs style1\">edit info </span>\r\n");
          out.write("          </a>\r\n        </td>\r\n        <td width=\"98\">\r\n          <a href=\"Contactus.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <span class=\"titlebig whitelhs style1\">contact us </span>\r\n          </a>\r\n        </td>\r\n        <td width=\"61\">\r\n          <a href=\"History.jsp\" target=\"_top\" onMouseOver=\"window.status='View Cart'; return true\" onMouseOut=\"window.status=''; return true\">\r\n            <span class=\"titlebig whitelhs style1\">History</span>\r\n          </a>\r\n        </td>\r\n        <td width=\"41\">&nbsp;</td>\r\n        <td width=\"28\">&nbsp;</td>\r\n      </tr>\r\n      <tr bgcolor=\"#ffffff\" valign=\"middle\">\r\n        <td colspan=\"12\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n        </td>\r\n      </tr>\r\n      <tr bgcolor=\"#00563b\" valign=\"middle\">\r\n        <td colspan=\"12\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n        </td>\r\n");
          out.write("      </tr>\r\n    </tbody>\r\n  </table>\r\n  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"5\">\r\n  <!-- END NAV//-->\r\n  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"780\">\r\n    <tbody>\r\n      <tr>\r\n        <td bgcolor=\"#ffffff\" valign=\"top\" width=\"144\">\r\n          <!-- LEFT HAND SIDE //-->\r\n<script language=\"javascript\" type=\"\">\r\n\t<!--\r\n\tfunction Form_ValidatorLHSSubmit(SubmitType) {\r\n\t\ttheForm = document.lhsform;\r\n\t\tif (Form_ValidatorLHS(theForm, SubmitType)) {\r\n\t\t\ttheForm.submit();\r\n\t\t}\r\n\t}\r\n\r\n\tfunction Form_ValidatorLHS(theForm, SubmitType) {\r\n\t\tif (SubmitType.toLowerCase() == \"search\") {\r\n\t\t\ttheForm.action = \"/search/results.asp\"\r\n\t\t\t// Validation script for field 'searchbycriteria' (Search Term)\r\nif (theForm.searchbycriteria.value == \"\")\r\n{\r\n\talert(\"Please enter a value for the \\\"Search Term\\\" field.\");\r\n   theForm.searchbycriteria.focus();\r\n   return (false);\r\n}\r\n\r\n\t\tif (theForm.searchbycriteria.value.length < 1)\r\n  \t{\r\n     \talert(\"Please enter at least 1 characters in the \\\"Search Term\\\" field.\");\r\n");
          out.write("     \ttheForm.searchbycriteria.focus();\r\n     \treturn (false);\r\n  \t}\r\n\r\n  \tif (theForm.searchbycriteria.value.length > 200)\r\n  \t{\r\n     \talert(\"Please enter at most 200 characters in the \\\"Search Term\\\" field.\");\r\n     \ttheForm.searchbycriteria.focus();\r\n     \treturn (false);\r\n  \t}\r\n\r\n\r\n\t\t} else {\r\n\t\t\ttheForm.action = \"/myaccount/login.asp\"\r\n\t\t\t  // Email field validation\r\n// Validation script for field 'email' (subscribing)\r\nif (theForm.email.value == \"\")\r\n{\r\n\talert(\"Please enter a value for the \\\"subscribing\\\" field.\");\r\n   theForm.email.focus();\r\n   return (false);\r\n}\r\n\r\n\t\tif (theForm.email.value.length < 1)\r\n  \t{\r\n     \talert(\"Please enter at least 1 characters in the \\\"subscribing\\\" field.\");\r\n     \ttheForm.email.focus();\r\n     \treturn (false);\r\n  \t}\r\n\r\n  \tif (theForm.email.value.length > 150)\r\n  \t{\r\n     \talert(\"Please enter at most 150 characters in the \\\"subscribing\\\" field.\");\r\n     \ttheForm.email.focus();\r\n     \treturn (false);\r\n  \t}\r\n\r\n  if (theForm.email.value.indexOf(\"@\",1) == -1)\r\n  {\r\n    alert(\"Not a valid e-mail address for subscribing.\");\r\n");
          out.write("    theForm.email.focus();\r\n    return (false);\r\n  }\r\n\r\n  if (theForm.email.value.indexOf(\".\",theForm.email.value.indexOf(\"@\")+1) == -1)\r\n  {\r\n    alert(\"Not a valid e-mail address for subscribing.\");\r\n    theForm.email.focus();\r\n    return (false);\r\n  }\r\n\r\n\r\n\t\t}\r\n\t\treturn true;\r\n\t}\r\n\t//-->\r\n\t</script>\r\n          <form method=\"get\" action=\"/search/results.asp\">\r\n          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"144\">\r\n            <tbody>\r\n              <tr>\r\n                <td valign=\"top\" width=\"9\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"9\">\r\n                </td>\r\n                <td colspan=\"2\" valign=\"top\" width=\"126\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"18\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/left_search.gif\" alt=\"Search\" border=\"0\" height=\"17\" width=\"47\"></td>\r\n                <td valign=\"top\" width=\"9\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"9\">\r\n");
          out.write("                </td>\r\n              </tr>\r\n              <tr>\r\n                <td>                </td>\r\n                <td colspan=\"2\" valign=\"top\" class=\"style6\" >\r\n                  &nbsp;<br>\r\n                    <form action=\"Search.jsp\" method=\"post\" >\r\n                      <input name=\"key\" value=\"\" class=\"lhstext126\" size=\"12\" type=\"text\">\r\n                    \t</form></td>\r\n                <td>                </td>\r\n              </tr>\r\n              <tr>\r\n                <td>                </td>\r\n                <td class=\"style7\">                \r\n                    \t<input name=\"Submit13\" type=\"submit\" value=\"Search\"></td>\r\n              </tr>\r\n              <tr>\r\n                <td colspan=\"4\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"8\" width=\"1\">\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td colspan=\"4\" bgcolor=\"#cccccc\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n");
          out.write("                </td>\r\n              </tr>\r\n              </tr>\r\n            </tbody>\r\n          </table>\r\n          </form>\r\n          <table bgcolor=\"#00563b\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"144\">\r\n            <tbody>\r\n              <tr>\r\n                <td valign=\"top\" width=\"9\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"9\">\r\n                </td>\r\n                <td valign=\"top\" width=\"135\">\r\n                  <span class=\"titlebig whitelhs style1\">Product</span>\r\n                </td>\r\n                <td>\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td>\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td class=\"whitelhs\" valign=\"top\">                  -\r\n                  <a href=\"http://www.angusrobertson.com.au/products/top100.asp\" class=\"whitelhs\">CD</a>\r\n");
          out.write("                  <br>\r\n                  -\r\n                  <a href=\"http://www.angusrobertson.com.au/products/bestsellers.asp\" class=\"whitelhs\">Book</a>\r\n                  <br>\r\n                  -\r\n                  <a href=\"http://www.angusrobertson.com.au/products/GuaranteedGreatReads.asp\" class=\"whitelhs\">Stationary</a>\r\n                  <br>\r\n                  <br>\r\n                  <br>\r\n                  <a href=\"http://www.angusrobertson.com.au/products/categories.asp\" class=\"whitelhs\">View All Categories</a>\r\n                </td>\r\n                <td>\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td colspan=\"3\" valign=\"top\">\r\n                  <img src=\"Template2_MMM.com_files/left_fade.gif\" alt=\"\" border=\"0\" height=\"250\" width=\"144\">\r\n                </td>\r\n              </tr>\r\n            </tbody>\r\n          </table>\r\n          <!-- END LEFT HAND SIDE //-->\r\n");
          out.write("        </td>\r\n        <td bgcolor=\"#999999\" valign=\"top\" width=\"1\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n        </td>\r\n        <td valign=\"top\" width=\"10\">\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"10\">\r\n        </td>\r\n        <td valign=\"top\" width=\"625\">\r\n          <!-- MAIN CONTENT //-->\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"18\" width=\"1\">\r\n          <br>\r\n          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"625\">\r\n            <tbody>\r\n              <tr>\r\n                <td valign=\"top\">\r\n                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <tbody>\r\n                      <tr>\r\n                        <td colspan=\"3\" bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"260\">\r\n                        </td>\r\n                      </tr>\r\n");
          out.write("                      <!--\r\n                        <tr>\r\n                        <td valign=\"top\" bgcolor=\"#CCCCCC\" colspan=\"1\"><img src=\"images/gap.gif\" width=\"1\" height=\"1\" alt=\"\" border=\"0\"></td>\r\n                        <td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\">\r\n                        <table cellspacing=\"9\" width=\"100%\"><tr>\r\n                        <td valign=\"top\" bgcolor=\"#00563B\" colspan=\"2\"><img src=\"images/gap.gif\" width=\"4\" height=\"1\" alt=\"\" border=\"0\"><img src=\"images/title_octcat.gif\" height=\"25\" alt=\"MMM November Catalogue\" border=\"0\"></td>\r\n                        </tr>\r\n                        </table>\r\n                        </td>\r\n                        <td valign=\"top\" bgcolor=\"#CCCCCC\"><img src=\"images/gap.gif\" width=\"1\" height=\"1\" alt=\"\" border=\"0\"></td>\r\n                        </tr>\r\n                      -->\r\n                      <tr>\r\n                        <td bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n");
          out.write("                        </td>\r\n                        <td align=\"center\" bgcolor=\"#ffffff\" valign=\"top\">\r\n                          <a href=\"http://top100.angusrobertson.com.au/\" target=\"_blank\">\r\n                            <img src=\"Template2_MMM.com_files/kirkdale_bookshop_01.jpg\" border=\"0\" height=\"178\" hspace=\"4\" vspace=\"4\" width=\"200\" alt=\"\">\r\n                          </a>\r\n                        </td>\r\n                        <td bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                        </td>\r\n                      </tr>\r\n                      <tr>\r\n                        <td colspan=\"3\" bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                        </td>\r\n                      </tr>\r\n                    </tbody>\r\n                  </table>\r\n                  <!--\r\n                    <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
          out.write("                    <tr><td valign=\"top\" colspan=\"3\" bgcolor=\"#CCCCCC\"><img src=\"images/gap.gif\" width=\"260\" height=\"1\" alt=\"\" border=\"0\"></td></tr>\r\n                    <tr>\r\n                    <td valign=\"top\" bgcolor=\"#CCCCCC\"><img src=\"images/gap.gif\" width=\"1\" height=\"1\" alt=\"\" border=\"0\"></td>\r\n                    <td valign=\"top\" bgcolor=\"#FFFFFF\"><a href=\"#\"><img src=\"images/arjan.gif\" width=\"250\" height=\"198\" alt=\"Angus & Robertson Online\" border=\"0\" hspace=\"4\" vspace=\"4\"></a></td>\r\n                    <td valign=\"top\" bgcolor=\"#FFFFFF\"><a href=\"#\"><img src=\"images/random1.jpg\" width=\"250\" height=\"215\" alt=\"Angus & Robertson Online\" border=\"0\" hspace=\"4\" vspace=\"4\"></a></td>\r\n                  -->\r\n                  <!--\r\n                    <td valign=\"top\" bgcolor=\"#FFFFFF\"><a href=\"http://www.booksalive.com.au/\" target=\"blank\"><img src=\"images/books-alive.gif\" width=\"250\" height=\"198\" alt=\"Kids' Top 50\" border=\"0\" hspace=\"4\" vspace=\"4\"></a></td>\r\n                    <td valign=\"top\" bgcolor=\"#CCCCCC\"><img src=\"images/gap.gif\" width=\"1\" height=\"1\" alt=\"\" border=\"0\"></td>\r\n");
          out.write("                    </tr>\r\n                    <tr><td valign=\"top\" colspan=\"3\" bgcolor=\"#CCCCCC\"><img src=\"images/gap.gif\" width=\"1\" height=\"1\" alt=\"\" border=\"0\"></td></tr>\r\n                    </table>\r\n                  -->\r\n                </td>\r\n                <td valign=\"top\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"10\">\r\n                </td>\r\n                <td valign=\"top\">\r\n                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <tbody>\r\n                      <tr>\r\n                        <td colspan=\"3\" bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"356\">\r\n                        </td>\r\n                      </tr>\r\n                      <tr>\r\n                        <td bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                        </td>\r\n");
          out.write("                        <td align=\"center\" bgcolor=\"#ffffff\" valign=\"top\" width=\"100%\">\r\n                          <a href=\"http://www.angusrobertson.com.au/products/harrypotter.asp\">\r\n                            <img src=\"Template2_MMM.com_files/n-cdshop.gif\" alt=\"A&amp;R Win! Promotion\" border=\"0\" height=\"177\" hspace=\"4\" vspace=\"4\" width=\"211\">\r\n                          </a>\r\n                        </td>\r\n                        <!--<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\"><img src=\"images/Big-Book-Sale1.gif\" width=\"345\" height=\"198\" alt=\"MMM Big Book Sale\" border=\"0\" hspace=\"4\" vspace=\"4\"></a></td>-->\r\n                        <td bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                        </td>\r\n                      </tr>\r\n                      <tr>\r\n                        <td colspan=\"3\" bgcolor=\"#cccccc\" valign=\"top\">\r\n                          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"356\">\r\n");
          out.write("                        </td>\r\n                      </tr>\r\n                    </tbody>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n            </tbody>\r\n          </table>\r\n          <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"9\" width=\"1\">\r\n          <table width=\"704\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n            <tbody>\r\n              <tr bgcolor=\"#cccccc\">\r\n                <td valign=\"top\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td valign=\"top\" width=\"264\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"264\">\r\n                </td>\r\n                <td valign=\"top\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td valign=\"top\" width=\"358\">&nbsp;</td>\r\n                <td valign=\"top\" width=\"1\">\r\n");
          out.write("                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n              </tr>\r\n              <tr bgcolor=\"#cccccc\">\r\n                <td valign=\"top\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td bgcolor=\"#ffffff\" valign=\"top\" width=\"264\">\r\n                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"376\">\r\n                    <tbody>\r\n                      <tr>\r\n                        <td width=\"358\" height=\"27\" valign=\"top\" bgcolor=\"#00563b\">\r\n                          <span class=\"style3\">Welcom </span>\r\n                        </td>\r\n                      </tr>\r\n                    </tbody>\r\n                  </table>\r\n                </td>\r\n                <td valign=\"top\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td width=\"356\" valign=\"top\" bgcolor=\"#00563b\">\r\n");
          out.write("                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"4\"/>\r\n                  <span class=\"style3\">Login</span>\r\n                </td>\r\n                <td valign=\"top\" width=\"1\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n              </tr>\r\n              <tr bgcolor=\"#cccccc\">\r\n                <td valign=\"top\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td bgcolor=\"#ffffff\" valign=\"top\">\r\n                  <p>\r\n                    <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                  </p>\r\n                  <p>\r\n                  <p>\r\n                    <span style=\"font-size:large\">Welcome to mmm.com e-store you can reach\r\nbooks, cd and stationaries just by one click. After seeing your favorite merchandize just after eye blick by click\r\n");
          out.write("it will be added to your cart.</span>\r\n                  </p>\r\n                  <p>                  </p>\r\n                  <p>                  </p>\r\n                  <p>\r\n                    <span style=\"font-size:x-large\"> if you are not registered\r\ndont worry you can sign up easier than anywhere just by one click here</span>\r\n\r\n                  <p>\r\n                  <form action=\"Signup.jsp\" method=\"POST\">\r\n                  <P align=\"center\">\r\n                    <input name=\"Submit12\" type=\"submit\" value=\"SignUp\" style=\"width:160px; height:43px; background-color:#3399FF; border-bottom-color:#00FFFF\"/>\r\n                  </p>\r\n                  </form>\r\n                </td>\r\n                <td valign=\"top\">\r\n                  <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n                </td>\r\n                <td align=\"right\" bgcolor=\"#ffffff\" valign=\"bottom\">\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
        }
      }
      out.write("\r\n<form method=\"POST\" action=\"Login.jsp\" style=\"height: 127px; width: 285px\">  User Name :\r\n<br/>\r\n<input name=\"UserName\" type=\"text\"/>\r\n<br/>\r\n  Password :\r\n<br/>\r\n<input name=\"Password\" type=\"password\"/>\r\n<br/>\r\n<input name=\"Submit1\" type=\"submit\" value=\"Login\"/>\r\n</form>\r\n<td valign=\"bottom\">\r\n  <img src=\"Template2_MMM.com_files/gapEEEEEE.gif\" alt=\"\" border=\"0\" height=\"26\" width=\"1\">\r\n</td>\r\n<tr bgcolor=\"#cccccc\">\r\n  <td colspan=\"5\" align=\"right\" valign=\"top\">\r\n    <img src=\"Template2_MMM.com_files/gapEEEEEE.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"13\">\r\n  </td>\r\n</tr>\r\n<br>\r\n<br>\r\n  <!-- END MAIN CONTENT //-->\r\n  <!-- FOOTER //-->\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"780\">\r\n  <tbody>\r\n    <tr valign=\"top\">\r\n      <td colspan=\"4\" bgcolor=\"#ffffff\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n      </td>\r\n    </tr>\r\n    <tr bgcolor=\"#00563b\" valign=\"middle\">\r\n      <td width=\"14\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"17\" width=\"14\">\r\n");
      out.write("      </td>\r\n      <td class=\"white\" width=\"376\"> Copyright MMM 2007</td>\r\n      <td align=\"right\" width=\"376\">\r\n        <a href=\"javascript:privacypolicy()\" class=\"footer\">Privacy Policy</a>\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"15\">\r\n        <a href=\"javascript:termsofuse()\" class=\"footer\">Terms of Use</a>\r\n      </td>\r\n      <td width=\"14\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"14\">\r\n      </td>\r\n    </tr>\r\n    <tr valign=\"top\">\r\n      <td colspan=\"4\" bgcolor=\"#00563b\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n      </td>\r\n    </tr>\r\n    <tr valign=\"top\">\r\n      <td colspan=\"4\" bgcolor=\"#ffffff\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n      </td>\r\n    </tr>\r\n    <tr valign=\"top\">\r\n      <td colspan=\"4\" bgcolor=\"#00563b\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"1\" width=\"1\">\r\n");
      out.write("      </td>\r\n    </tr>\r\n    <tr valign=\"top\">\r\n      <td colspan=\"4\">\r\n        <img src=\"Template2_MMM.com_files/gap.gif\" alt=\"\" border=\"0\" height=\"2\" width=\"1\">\r\n      </td>\r\n    </tr>\r\n    <tr valign=\"top\">\r\n      <td>      </td>\r\n      <td class=\"grey666666\">WWW.MMM.COM</td>\r\n      <td class=\"grey666666\" align=\"right\">        Site designed by\r\n        <a href=\"http://www.spin.com.au/\" target=\"_blank\" class=\"darkgreen\">MMM</a>\r\n      </td>\r\n      <td>      </td>\r\n    </tr>\r\n  </tbody>\r\n</table>\r\n  <!-- EOF -->\r\n</body>\r\n</html>\r\n\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
