package chat.cliente;


/**
* chat/cliente/ClientListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ChatServide.idl
* Quarta-feira, 2 de Junho de 2004 19h33min52s GMT-03:00
*/

public abstract class ClientListenerPOA extends org.omg.PortableServer.Servant
 implements chat.cliente.ClientListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addApelido", new java.lang.Integer (0));
    _methods.put ("delApelido", new java.lang.Integer (1));
    _methods.put ("recebeMensagem", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/cliente/ClientListener/addApelido
       {
         String apelido = in.read_string ();
         this.addApelido (apelido);
         out = $rh.createReply();
         break;
       }

       case 1:  // chat/cliente/ClientListener/delApelido
       {
         String apelido = in.read_string ();
         this.delApelido (apelido);
         out = $rh.createReply();
         break;
       }

       case 2:  // chat/cliente/ClientListener/recebeMensagem
       {
         chat.Mensagem msg = chat.MensagemHelper.read (in);
         this.recebeMensagem (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/cliente/ClientListener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientListener _this() 
  {
    return ClientListenerHelper.narrow(
    super._this_object());
  }

  public ClientListener _this(org.omg.CORBA.ORB orb) 
  {
    return ClientListenerHelper.narrow(
    super._this_object(orb));
  }


} // class ClientListenerPOA
