package chat.cliente;

/**
* chat/cliente/ClientListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ChatServide.idl
* Quarta-feira, 2 de Junho de 2004 19h33min52s GMT-03:00
*/

public final class ClientListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.cliente.ClientListener value = null;

  public ClientListenerHolder ()
  {
  }

  public ClientListenerHolder (chat.cliente.ClientListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.cliente.ClientListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.cliente.ClientListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.cliente.ClientListenerHelper.type ();
  }

}
