; COM file is loaded at CS:0100h
ORG 100h
.MODEL	SMALL
.CODE
ORG	100H
BEGIN:	JMP	SHORT MAIN
CHAR	DB	00, '$'

;	MAIN PROCEDURE:
;	----------------------
MAIN	PROC 	NEAR
	CALL	B10CLR	;CLEAR SCREEN
	CALL	C10SET	;SET CURSOR
	CALL	D10DISP	;DISPLAY CHARACTERS
	MOV 	AX,4C00H	;EXIT TO DOS
	INT	21H
MAIN	ENDP
;	CLEAR SCREEN:
;	-------------------------
B10CLR	PROC	NEAR
	MOV	AX, 0600H	;SCROLL	FULL SCREEN
	MOV 	BH,07		;ATTRIB: WH ON BLK
	MOV	CX,0000		;UPPER LEFT LOC
	MOV 	DX, 184FH	;LOWER	RIGHT LOC
	INT	10H
	RET
B10CLR	ENDP
;	SET CURSOR TO 00,00:
;	--------------------------
C10SET	PROC	NEAR
	MOV	AH, 02H		;REQUEST SET CURSOR
	MOV 	BH,00		;PAGE NUMBER 0
	MOV 	DX,0000		;ROW 0,	COLUMN 0
	INT 	10H
	RET
C10SET	ENDP
;	DISPLAY AXCII CHARACTERS:
;	------------------------------
D10DISP	PROC
	MOV	CX, 256		;DO 256 ITERATIONS
	LEA	DX,CHAR		;INIT ADDR OF CHAR
D20:
	MOV 	AH, 09H		;DISPLAY ASCII CHAR
	INT	21H
	INC	CHAR		;INCR	for next char
	LOOP	D20		;DO 256	TIMES
	RET
D10DISP	ENDP
	END	BEGIN