package chat.servidor;


/**
* chat/servidor/ChatServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ChatServide.idl
* Quarta-feira, 2 de Junho de 2004 19h33min52s GMT-03:00
*/

public interface ChatServiceOperations 
{
  String[] conectar (String apelido, chat.cliente.ClientListener listener);
  void desconectar (String apelido, chat.cliente.ClientListener listener);
  void enviaMensagem (String apelido, chat.Mensagem msg);
} // interface ChatServiceOperations
