package chat;


/**
* chat/ListaClientesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ChatServide.idl
* Quarta-feira, 2 de Junho de 2004 19h33min52s GMT-03:00
*/

public final class ListaClientesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListaClientesHolder ()
  {
  }

  public ListaClientesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ListaClientesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ListaClientesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ListaClientesHelper.type ();
  }

}
