package chat;


/**
* chat/Mensagem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ChatServide.idl
* Quarta-feira, 2 de Junho de 2004 19h33min52s GMT-03:00
*/

public final class Mensagem implements org.omg.CORBA.portable.IDLEntity
{
  public String origem = null;
  public String mensagem = null;

  public Mensagem ()
  {
  } // ctor

  public Mensagem (String _origem, String _mensagem)
  {
    origem = _origem;
    mensagem = _mensagem;
  } // ctor

} // class Mensagem
