#make_COM#

; COM file is loaded at CS:0100h
ORG 100h

.MODEL	SMALL
.CODE
ORG	100H
BEGIN:	JMP	SHORT, 	MAIN
InList	LABEL	BYTE	;A PLACE HOLDER
MaxChar	DB	6	;ZIP CODE PLUS CR
Actual	DB	?	;GET BACK # TYPED
ZipCode	DB	6	DUP(?)

;	MAIN PROCEDURE:
;	----------------------
MAIN	PROC 	NEAR
	CALL	B10CLR	;CLEAR SCREEN
	CALL	C10SET	;SET CURSOR
	CALL	D10DISP	;DISPLAY CHARACTERS
	MOV 	AX,4C00H	;EXIT TO DOS
	INT	21H
MAIN	ENDP
;	CLEAR SCREEN:
;	-------------------------
B10CLR	PROC	NEAR
	MOV	AX, 0600H	;SCROLL	FULL SCREEN
	MOV 	BH,07		;ATTRIB: WH ON BLK
	MOV	CX,0000		;UPPER LEFT LOC
	MOV 	DX, 184FH	;LOWER	RIGHT LOC
	INT	10H
	RET
B10CLR	ENDP
;	SET CURSOR TO 00,00:
;	--------------------------
C10SET	PROC	NEAR
	MOV	AH, 02H		;REQUEST SET CURSOR
	MOV 	BH,00		;PAGE NUMBER 0
	MOV 	DX,0000		;ROW 0,	COLUMN 0
	INT 	10H
	RET
C10SET	ENDP
;	DISPLAY AXCII CHARACTERS:
;	------------------------------
D10DISP	PROC
	MOV	AH,0Ah		;KEYBOARD INPUT
	LEA	DX,InList	;GIVE P-LIST
	INT	21H
D10DISP	ENDP
	END	BEGIN