######################################################################
# Automatically generated by qmake (1.07a) Fri Jun 30 16:25:15 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myserversocket.h serverform.ui.h
INTERFACES += serverform.ui
SOURCES += myserversocket.cpp server.cpp
