######################################################################
# Automatically generated by qmake (1.07a) Fri Jun 30 15:39:54 2006
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
INTERFACES += clientform.ui
SOURCES += client.cpp
